<?php
/*
 * Created by PhpStorm.
 *
 * User: zOmArRD
 * Date: 25/11/2021
 *
 * Copyright © 2021 Ghostly GExtension - All Rights Reserved.
 */
declare(strict_types=1);

namespace core\ghostly;

use core\ghostly\modules\mysql\AsyncQueue;
use core\ghostly\modules\mysql\query\InsertQuery;
use pocketmine\network\mcpe\RakLibInterface;
use pocketmine\plugin\PluginBase;
use pocketmine\plugin\PluginLogger;
use zomarrd\core\task\TaskManager;

class Ghostly extends PluginBase
{
    /** @var Ghostly */
    public static Ghostly $ghostly;

    /** @var PluginLogger */
    public static PluginLogger $logger;

    public function onLoad(): void
    {
        self::$ghostly = $this;
        self::$logger = $this->getLogger();

        $this->MySQLScan();
    }

    public function onEnable(): void
    {
        /* Avoid some network crashes when transferring packets */
        foreach ($this->getServer()->getNetwork()->getInterfaces() as $interface) if ($interface instanceof RakLibInterface) $interface->setPacketLimit(PHP_INT_MAX);

        new TaskManager();
    }

    public function onDisable(): void
    {
        parent::onDisable(); // TODO: Change the autogenerated stub
    }

    /**
     * @return Ghostly
     */
    public static function getGhostly(): Ghostly
    {
        return self::$ghostly;
    }

    /**
     * @todo add more tables.
     */
    public function MySQLScan(): void
    {
        self::$logger->info("Analyzing the database");
        AsyncQueue::submitQuery(new InsertQuery("CREATE TABLE IF NOT EXISTS settings(player TEXT, lang TEXT, scoreboard SMALLINT DEFAULT 1);"));
    }
}